// Instant, zero-network results for popular words under the default filters.
//
// `prefetch.json` (generated by scripts/gen_prefetch.py) holds the exact
// /api/search payload for a handful of frequently-searched keywords, computed
// for the default explorer filter signature: no party/MP filter, the current
// legislature only, quarterly granularity, occurrences mode, top 15 speakers.
//
// When a query matches that signature *and* the word is in the bundle, the
// explorer can render charts the instant the page loads — no API round-trip,
// no full-text scan. Anything else (other term, a filter, monthly view,
// speeches mode, an unlisted word) returns null and falls back to the live API.

import bundle from './prefetch.json';
import type { Filters, SearchResult } from './types';

interface PrefetchBundle {
	signature: {
		terms: number[];
		granularity: string;
		count_mode: string;
		top_n: number;
	};
	words: Record<string, SearchResult>;
}

const { signature, words } = bundle as unknown as PrefetchBundle;

function sameTerms(a: number[], b: number[]): boolean {
	if (a.length !== b.length) return false;
	const sa = [...a].sort((x, y) => x - y);
	const sb = [...b].sort((x, y) => x - y);
	return sa.every((v, i) => v === sb[i]);
}

/**
 * Return a precomputed SearchResult when `f`/`topN` match the default filter
 * signature and the word is bundled; otherwise null (caller hits the API).
 */
export function prefetchSearch(f: Filters, topN: number): SearchResult | null {
	if (f.parties.length || f.politician_id != null || f.date_from || f.date_to) return null;
	if (f.granularity !== signature.granularity || f.count_mode !== signature.count_mode) return null;
	if (topN !== signature.top_n) return null;
	if (!sameTerms(f.terms, signature.terms)) return null;

	const key = (f.word ?? '').trim().toLowerCase();
	return words[key] ?? null;
}
